import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import các component bạn vừa tạo
import { AuthProvider } from "@/context/AuthContext";
import LayoutManager from "@/components/layout/LayoutManager";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'; // BẮT BUỘC ĐỂ CÓ CSS PROGRESS BAR
import Providers from "./Providers/providers"
import AOSProvider from "./Providers/AOSProvider";
import { ThemeProvider } from "next-themes";
import ThemeToggle from "@/components/ui/ThemeToggle";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* AuthProvider được bọc ở mức cao nhất để mọi component bên trong đều dùng được */}
        <AuthProvider>
          <Providers>
            <AOSProvider>
              <LayoutManager>{children} </LayoutManager>
            </AOSProvider>
            <ToastContainer 
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={true}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
